GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "John",
    "number": "12345678"
}

###
GET https://render-phonebook-qpy0.onrender.com/api/persons

###
POST https://render-phonebook-qpy0.onrender.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "John",
    "number": "12345678"
}